"""
ステージマスターデータ定義
"""

from typing import List, Union
from .map_master import MAP_MASTER_LIST


class EnemySpawnData:
    """
    1体のエネミー出現情報
    """

    def __init__(self, enemy_type: str, spawn_point: tuple[int, int], coefficient: float):
        self.enemy_type = enemy_type
        self.spawn_point = spawn_point
        self.coefficient = coefficient


class FlyingEnemySpawnData(EnemySpawnData):
    """
    飛行エネミー用の出現情報（着地地点を追加）
    """

    def __init__(self, spawn_point: tuple[int, int], landing_point: tuple[int, int], coefficient: float):
        super().__init__("FlyingEnemy", spawn_point, coefficient)
        self.landing_point = landing_point


class Delay:
    """
    エネミー出現間の待機時間を表すクラス。
    """

    def __init__(self, frame: int):
        self.frame = frame


class StageWaveData:
    """
    1ウェーブの出現情報
    spawns: [EnemySpawnData, Delay, ...] のようなリスト
    """

    def __init__(self, spawns: List[Union[EnemySpawnData, Delay]]):
        self.spawns = spawns


class StageMasterData:
    """
    ステージ全体のマスターデータ
    """

    def __init__(self, map_id: int, map_data: list[list[int]], waves: List[StageWaveData]):
        self.map_id = map_id
        self.map_data = map_data  # 2次元リストのマップデータ
        self.waves = waves


# --- ステージごとのマスターデータリスト ---
STAGE_MASTER_LIST = [
    StageMasterData(
        map_id=1,
        map_data=MAP_MASTER_LIST[0],
        waves=[
            # (3, 0), (8, 0), (7, 12) が入口
            StageWaveData(
                [
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 0), coefficient=1.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(7, 12), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(3, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(3, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(3, 0), coefficient=3.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(9, 0), landing_point=(11, 8), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 0), coefficient=3.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(3, 0), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 0), coefficient=6.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(0, 5), landing_point=(8, 9), coefficient=6.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(0, 5), landing_point=(8, 9), coefficient=6.0),
                ]
            ),
            StageWaveData([]),
        ],
    ),
    StageMasterData(
        map_id=2,
        map_data=MAP_MASTER_LIST[1],
        waves=[
            # (0, 1), (16, 1), (14, 11)が入口
            StageWaveData(
                [
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=2.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=2.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=2.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 1), coefficient=2.5),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(0, 9), landing_point=(12, 8), coefficient=3),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(0, 9), landing_point=(12, 8), coefficient=3),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(0, 9), landing_point=(12, 8), coefficient=3),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(0, 9), landing_point=(12, 8), coefficient=3),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=3.0),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(4, 0), landing_point=(8, 9), coefficient=3.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=3.0),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(4, 0), landing_point=(8, 9), coefficient=3.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=3.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=4.0),
                    Delay(40),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=4.0),
                    Delay(40),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=4.0),
                    Delay(40),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=4.0),
                    Delay(40),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=4.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=4.0),
                    Delay(30),
                    FlyingEnemySpawnData(spawn_point=(0, 11), landing_point=(12, 8), coefficient=6.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(0, 11), landing_point=(12, 8), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=5.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(0, 1), coefficient=5.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=5.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(0, 1), coefficient=5.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(16, 1), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(0, 1), coefficient=5.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=6),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=6),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=6),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=6),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=6.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=6.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=6.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=6.5),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=6.5),
                    Delay(90),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(14, 11), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 1), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=7.5),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=7.5),
                    Delay(40),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=7.5),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=7.5),
                    Delay(40),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=7.5),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=7.5),
                    Delay(40),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=7.5),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(14, 11), coefficient=7.5),
                    Delay(40),
                    FlyingEnemySpawnData(spawn_point=(4, 0), landing_point=(6, 8), coefficient=10.0),
                    Delay(180),
                    FlyingEnemySpawnData(spawn_point=(4, 0), landing_point=(6, 8), coefficient=10.0),
                    Delay(180),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=12.0),
                    Delay(180),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=12.0),
                    Delay(180),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=12.0),
                    Delay(180),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(0, 1), coefficient=12.0),
                ]
            ),
        ],
    ),
    StageMasterData(
        map_id=3,
        map_data=MAP_MASTER_LIST[2],
        waves=[
            # (10, 0), (16, 0), (26, 8), (26, 14), (8, 18)が入口
            StageWaveData(
                [
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=1.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=1.0),
                    Delay(50),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=1.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=1.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=1.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=1.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=1.5),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=2.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=2.0),
                    Delay(50),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=1.0),
                    Delay(30),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 18), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 18), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 18), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(8, 18), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 8), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 8), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 8), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 8), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=2.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 14), coefficient=3.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=3.5),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=4.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=4.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=4.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(15, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(15, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(15, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(15, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(11, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(11, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(11, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(13, 0), landing_point=(11, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 5), landing_point=(4, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 5), landing_point=(4, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 5), landing_point=(4, 7), coefficient=4.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 5), landing_point=(4, 7), coefficient=4.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=8.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=8.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=5.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=6.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=6.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=6.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=6.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(10, 0), coefficient=6.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(16, 0), coefficient=6.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(26, 14), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(10, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(10, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(10, 0), coefficient=6.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=7.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=7.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=7.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=7.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=7.0),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=7.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=8.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=8.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=8.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=8.0),
                    Delay(90),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=8.0),
                    EnemySpawnData(enemy_type="FastEnemy", spawn_point=(8, 18), coefficient=8.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 8), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=12.0),
                    Delay(120),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(10, 0), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(16, 0), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(26, 14), coefficient=12.0),
                    EnemySpawnData(enemy_type="BasicEnemy", spawn_point=(8, 18), coefficient=12.0),
                    Delay(120),
                    FlyingEnemySpawnData(spawn_point=(26, 12), landing_point=(4, 7), coefficient=9.0),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=9.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 12), landing_point=(4, 7), coefficient=9.0),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=9.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 12), landing_point=(4, 7), coefficient=9.0),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=9.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 12), landing_point=(4, 7), coefficient=9.0),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=9.0),
                    Delay(60),
                    FlyingEnemySpawnData(spawn_point=(26, 12), landing_point=(4, 7), coefficient=9.0),
                    FlyingEnemySpawnData(spawn_point=(20, 18), landing_point=(10, 12), coefficient=9.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=17.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=17.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=17.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=17.0),
                    Delay(60),
                    EnemySpawnData(enemy_type="TankEnemy", spawn_point=(26, 8), coefficient=17.0),
                    Delay(60),
                ]
            ),
        ],
    ),
]
